services:
  - type: web
    name: construction-photos
    env: ruby
    region: oregon
    plan: free
    buildCommand: "bundle install && bundle exec rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: construction-photos-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-northeast-1
      - key: S3_BUCKET
        value: construction-photos-app

databases:
  - name: construction-photos-db
    plan: free